spring:
  datasource:
    url: jdbc:mysql://sspoid-rds.cn24k4e0mw5n.ap-northeast-2.rds.amazonaws.com:3306/sspoid_db?serverTimezone=Asia/Seoul&useSSL=false
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: false

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html  # Swagger UI 접속 경로
  api-docs:
    enabled: true
    path: /v3/api-docs       # 내부적으로 API 명세를 제공하는 경로

#model:
#  api:
#    url: http://localhost:5000/api/generate //??
