spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sspoid_db?useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: "/actuator"
  prometheus:
    metrics:
      export:
        enabled: true
