server:
  port: 8080
  forward-headers-strategy: framework
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true

spring:
  profiles:
    active: prod

kakao:
  api-key: ${API_KEY} # 암호화 필요
  redirect-uri: http://localhost:8080/api/login/kakao
